- name: configure Docker
  vars_prompt:
  - name: d_name
    prompt: Enter Container Name
    private: no


  hosts: localhost
  tasks:
          - name: Configure yum for docker
            yum_repository:
                    name: Docker
                    description: Docker_Repo
                    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
                    gpgcheck: no
                    enabled: yes
                    state: present
          - name: Installing Docker package
            package:
                    name:
                            - "docker-ce-18.09.1-3.el7.x86_64"
                    state: present
          - name: Start Docker service
            service:
                    name: "docker"
                    state: started
                    enabled: yes
          - name: Installing Python3
            package:
                    name:
                            - "python36"
          - name: Installing docker sdk
            command: pip3 install docker

          - name: Create Docker Container
            docker_container:
                    name: "{{ d_name }}"
                    image: "sheetal26/docker_ssh:v1"
                    state: started
                    interactive: yes
                    detach: yes
                    tty: yes
                    ports:
                            - "5001:80"
                            - "5002:22"
            register: x
          - debug:
                  var: x.container.NetworkSettings.IPAddress

          - name: updating inventory
            blockinfile:
                    path: "/etc/ansible/hosts"
                    block: |
                            [Docker]
                            {{x['container']['NetworkSettings']['IPAddress']}} ansible_ssh_user=root ansible_ssh_pass=redhat ansible_connection=ssh
